### ISSUE TITLE
Electrode Material, Analog Ground Biasing To Human Body

### ISSUE THREAD

**Issue by whathisface** [Mic-Tsai/Sensor_ECG_PPG_MAX86150_Dev-Board#1]
Hello @Mic-Tsai,

Nice work.

I have a question regarding your electrodes - what are they made of?  SST 316?  And, what is the method of attachment?
Are the backs of the electrodes bare metal or is there an insulator on the back?

Your analog ground circuit is interesting - are there any issues with static electricity doing that?

Thanks in advance,
whf

**Comment by Mic-Tsai** [comment]
Hi whf,

Electrodes - it’s general pcb copper with HASL (hot air slider leveling). Conductive material will work perfectly (even a clean coin) but, if you consider product reliability…steel wins. Back electrode is the same reference PAD on top (depend on hand measuring position).

Ground - the most interesting issue in bio sensing, prevent your system noise cross-talk to analog level, isolate power/ground…not supply with USB. (AC noise terrible)

Hardware attachment is EAGLE PCB design.

Enjoy😁

Mic

**Comment by whathisface** [comment]
Hello Mic,

OK - thanks for the response.
- whf
